// Code generated by goctl. DO NOT EDIT!
// Source: favorite.proto

package favoriterpc

import (
	"context"

	"DouYin/server/favorite/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FavoriteActionReq  = __.FavoriteActionReq
	FavoriteActionResp = __.FavoriteActionResp
	FavoriteListReq    = __.FavoriteListReq
	FavoriteListResp   = __.FavoriteListResp
	Video              = __.Video

	FavoriteRpc interface {
		// 赞操作
		FavoriteAction(ctx context.Context, in *FavoriteActionReq, opts ...grpc.CallOption) (*FavoriteActionResp, error)
		// 喜欢列表
		FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error)
	}

	defaultFavoriteRpc struct {
		cli zrpc.Client
	}
)

func NewFavoriteRpc(cli zrpc.Client) FavoriteRpc {
	return &defaultFavoriteRpc{
		cli: cli,
	}
}

// 赞操作
func (m *defaultFavoriteRpc) FavoriteAction(ctx context.Context, in *FavoriteActionReq, opts ...grpc.CallOption) (*FavoriteActionResp, error) {
	client := __.NewFavoriteRpcClient(m.cli.Conn())
	return client.FavoriteAction(ctx, in, opts...)
}

// 喜欢列表
func (m *defaultFavoriteRpc) FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error) {
	client := __.NewFavoriteRpcClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}
