// Code generated by goctl. DO NOT EDIT!
// Source: feed.proto

package server

import (
	"context"

	"DouYin/server/feed/pb"
	"DouYin/server/feed/rpc/internal/logic"
	"DouYin/server/feed/rpc/internal/svc"
)

type FeedRpcServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedFeedRpcServer
}

func NewFeedRpcServer(svcCtx *svc.ServiceContext) *FeedRpcServer {
	return &FeedRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *FeedRpcServer) Feed(ctx context.Context, in *__.FeedReq) (*__.FeedResp, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}
