// Code generated by goctl. DO NOT EDIT!
// Source: publish.proto

package server

import (
	"context"

	"DouYin/server/publish/pb"
	"DouYin/server/publish/rpc/internal/logic"
	"DouYin/server/publish/rpc/internal/svc"
)

type PublishRpcServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedPublishRpcServer
}

func NewPublishRpcServer(svcCtx *svc.ServiceContext) *PublishRpcServer {
	return &PublishRpcServer{
		svcCtx: svcCtx,
	}
}

// 视频投稿
func (s *PublishRpcServer) PublishAction(ctx context.Context, in *__.PublishActionReq) (*__.PublishActionResp, error) {
	l := logic.NewPublishActionLogic(ctx, s.svcCtx)
	return l.PublishAction(in)
}

// 发布列表
func (s *PublishRpcServer) PublishList(ctx context.Context, in *__.PublishListReq) (*__.PublishListResp, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}
