// Code generated by goctl. DO NOT EDIT!
// Source: favorite.proto

package server

import (
	"context"

	"DouYin/server/favorite/pb"
	"DouYin/server/favorite/rpc/internal/logic"
	"DouYin/server/favorite/rpc/internal/svc"
)

type FavoriteRpcServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedFavoriteRpcServer
}

func NewFavoriteRpcServer(svcCtx *svc.ServiceContext) *FavoriteRpcServer {
	return &FavoriteRpcServer{
		svcCtx: svcCtx,
	}
}

// 赞操作
func (s *FavoriteRpcServer) FavoriteAction(ctx context.Context, in *__.FavoriteActionReq) (*__.FavoriteActionResp, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

// 喜欢列表
func (s *FavoriteRpcServer) FavoriteList(ctx context.Context, in *__.FavoriteListReq) (*__.FavoriteListResp, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}
