// Code generated by goctl. DO NOT EDIT!
// Source: comment.proto

package server

import (
	"context"

	"DouYin/server/comment/pb"
	"DouYin/server/comment/rpc/internal/logic"
	"DouYin/server/comment/rpc/internal/svc"
)

type CommentRpcServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedCommentRpcServer
}

func NewCommentRpcServer(svcCtx *svc.ServiceContext) *CommentRpcServer {
	return &CommentRpcServer{
		svcCtx: svcCtx,
	}
}

// 评论操作
func (s *CommentRpcServer) CommentAction(ctx context.Context, in *__.CommentActionReq) (*__.CommentActionResp, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}

// 评论列表
func (s *CommentRpcServer) CommentList(ctx context.Context, in *__.CommentListReq) (*__.CommentListResp, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
